services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CormenA!**
      PGDATA: /data/postgres
      POSTGRES_DB: cormenai
    ports:
      - "5332:5432"
    networks:
      - cormenai-network
    restart: always

  mss-noticias:
        container_name: mss-noticias
        restart: always
        build:
            context: ./mss-noticias
            dockerfile: Dockerfile
        ports:
            - 3001:3001
        networks:
            - cormenai-network

  mss-login:
        container_name: mss-login
        restart: always
        build:
            context: ./mss-login
            dockerfile: Dockerfile
        ports:
            - 3002:3002
        networks:
            - cormenai-network

networks:
    cormenai-network:
        driver: bridge