apiVersion: v1
kind: Service
metadata:
  name: mss-login-service
spec:
  #porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: mss-login
  ports:
    - name: mss-login
      protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 31507