# FILEPATH: /home/sociopj/Socio/Maua/2023/ArquiteturaSistemas/cormen-ai-solutions/kubernetes/mss-noticias-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mss-noticias-service
spec:
  selector:
    app: mss-noticias
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
