apiVersion: v1
kind: Service
metadata:
  name: mss-noticias-service
spec:
  #porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: mss-noticias
  ports:
    - name: mss-noticias
      protocol: TCP
      port: 3001
      targetPort: 3001