apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres   # Use o rótulo apropriado que corresponde aos pods do PostgreSQL
  ports:
    - protocol: TCP
      port: 5432    # Porta padrão do PostgreSQ